import Head from 'next/head'
import Link from 'next/link';
import { motion } from "framer-motion"


import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Quentin Roggy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <motion.div 
            initial={{ opacity: 0, translateY: 20 }} 
            whileInView={{ opacity: 1, translateY: 0, transition: {duration: 0.8} }}>
            <h1>HEY, I&apos;M <span>QUENTIN ROGGY</span></h1>
          </motion.div>
          <motion.div 
            initial={{ opacity: 0, translateY: 20 }} 
            whileInView={{ opacity: 1, translateY: 0, transition: {duration: 0.8, delay: 0.5} }}>
            <h3>I&apos;am a fullstack developper working with React and Node.js</h3>
          </motion.div>
          <motion.div 
            initial={{ opacity: 0, translateY: 20 }} 
            whileInView={{ opacity: 1, translateY: 0, transition: {duration: 0.8, delay: 1} }}
            className={styles.about_container}>
            <Link className={styles.about_link} href='/about' >
              <Image 
                className={styles.arrow} 
                src="https://www.svgrepo.com/show/466032/right-arrow.svg" 
                alt="right arrow"
                width={24}
                height={24}
                />
                <span>About me</span>
            </Link>
          </motion.div>
        </div>
      </main>
    </>
  )
}
