import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import styles from '../styles/Projects.module.css';
import { useState } from 'react';

export default function Projects (props) {

  const [file, setFile] = useState('');

  const handleOnFocus = async (imgFocused) => {
    setFile(imgFocused);
    
  }
  return (
    <>
      <Head>
        <title>Quentin Roggy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.container}>
      <h1 className={styles.title}>Projects</h1>
      <div className={styles.projects_container}>
      <section className={styles.project_container_img_container}>
        {
          file && 
          <div 
            className={styles.project_image}
            style={{backgroundImage: `url(${file})`}}
          />
        }
      </section>
      <section className={styles.project_container_list_container}>
        {
          props.projects.map((project) => (
            <>
              <Link
                key={project.id}
                onMouseEnter={() => handleOnFocus(project.img)} 
                className={styles.project_container_list_item} 
                href={project.url} >

                <div className={styles.project_item_content}>
                <Image 
                  className={styles.arrow} 
                  src="https://www.svgrepo.com/show/466032/right-arrow.svg" 
                  alt="right arrow"
                  width={24}
                  height={24}
                />
                <span>{project.name}</span>
                </div>

              </Link>
            </>
          ))
        }
      </section>
      </div>
    </div>
    </>
  )
}

export async function getStaticProps() {
  const data = await import('/data/projects.json');
  const projects = data.projects;

  return {
    props: {
      projects,
    }
  }
}